src/routes/api.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime

from flask import Blueprint, current_app, request
from flask_login import current_user, login_required

from models import db
from models.game import Game
from models.game_user import GameUser
from models.user import UserRole

api_bp = Blueprint("api", __name__)

@api_bp.get("/games/<int:game_id>")
@login_required
def get_game(game_id):
    filters = [Game.id == game_id]
    
    if current_user.role != UserRole.ADMIN.value:
        filters.append(GameUser.user_id == current_user.id)
    
    if not (game := Game.query.join(GameUser).filter(*filters).first()):
        return {"success": False, "message": "Game not found"}, 404

    return {"success": True, "data": game.to_dict()}, 200


@api_bp.get("/games")
@login_required
def search_games():
    filters = []

    if slot := request.args.get("slot"):
        try:
            slot = datetime.strptime(slot, "%Y-%m-%dT%H:%M:%S").replace(minute=0, second=0)
            filters.append(Game.slot == slot)
        except ValueError:
            return {"success": False, "message": "Invalid date format, must be %Y-%m-%dT%H:%M:%S"}, 400

    if current_user.role != UserRole.ADMIN.value:
        filters.append(GameUser.user_id == current_user.id)
    elif user_id := request.args.get("user_id"):
        filters.append(GameUser.user_id == user_id)

    games = Game.query.join(GameUser).filter(*filters).all()
    return {"success": True, "data": [game.to_dict() for game in games]}, 200


@api_bp.post("/games")
@login_required
def create_game():
    data = request.get_json()

    if not (slots := data.get("slots")):
        return {"success": False, "message": "<slot> field is required"}, 400

    games = []
    current_slot_date = datetime.now().replace(minute=59, second=59)
    
    for slot in slots:
        try:
            slot = datetime.strptime(slot, "%Y-%m-%dT%H:%M:%S").replace(minute=0, second=0)
        except ValueError:
            return {"success": False, "message": "Invalid date format, must be %Y-%m-%dT%H:%M:%S"}, 400

        if not (9 <= slot.hour <= 23):
            return {"success": False, "message": "Games can only be made between 9 and 23"}, 400

        if slot < current_slot_date:
            return {"success": False, "message": "Cannot create a game in the past"}, 400

        game = Game.query.join(GameUser).filter(Game.slot == slot).first()
        
        if game:
            if current_user.id in map(lambda game_user: game_user.user_id, game.players):
                # Potrebbe non essere bloccante, e continuare ad inserire gli eventuali slot successivi
                return {"success": False, "message": "You already have a reservation for that slot"}, 409

            if len(game.players) >= current_app.players_for_game:
                return {"success": False, "message": "There is already a full game scheduled for that slot"}, 409
        else:
            game = Game(slot=slot, created_by=current_user.id)
            db.session.add(game)
        
        games.append(game)

        game_user = GameUser(game=game, user=current_user)
        db.session.add(game_user)

    db.session.commit()

    for game in games:
        # Ci sono abbastanza giocatori per iniziare una partita
        if len(game.players) == current_app.players_for_game:
            # Logica per l'invio di email/notifica, maniera asincrona
            # (Celery+Redis, ad esempio, oppure scheduler in background)
            pass

    return {"success": True, "data": [game.to_dict() for game in games]}, 201

@api_bp.delete("/games/<int:game_id>")
@login_required
def delete_game(game_id):
    if not (game := Game.query.join(GameUser).filter(Game.id == game_id).first()):
        return {"success": False, "message": "Game not found"}, 404

    my_reservation = next((player for player in game.players if player.user_id == current_user.id), None)
    if not my_reservation:
        return {"success": False, "message": "Reservation not found"}, 404

    if game.slot < datetime.now():
        return {"success": False, "message": "Cannot delete past or in progress game"}, 400

    # TODO: Un admin potrebbe voler eliminare un game con tutti i suoi giocatori,
    # oppure soltanto la prenotazione di giocatori specifici
   
    db.session.delete(game if len(game.players) <= 1 else my_reservation)
    db.session.commit()

    return {"success": True}

src/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Dashboard | PadelTime</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap/dist/css/bootstrap.min.css">
    <!-- Bootstrap Icons CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <style>
        html,
        body {
            height: 100%;
        }

        .wrapper {
            display: flex;
            flex-direction: column;
            min-height: 100%;
        }

        .content {
            flex: 1;
        }
    </style>

<body>
    <div class="wrapper">

        <header>
            <nav class="navbar navbar-expand-ld border-bottom border-body navbar-dark bg-dark">
                <div class="container">
                    <a class="navbar-brand" href="#">🏓 PadelTime</a>
                </div>
            </nav>
        </header>

        <main class="container mt-5 content">
            <div class="row align-items-center">
                <div class="col">
                    <h2>Your games</h2>
                </div>
                <div class="col-auto">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                        data-bs-target="#createGameModal">New game</button>
                </div>
            </div>
            <table id="gamesTable" class="table table-striped mt-3">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Slot</th>
                        <th>Organizer</th>
                        <th># Players</th>
                        <th>Ready?</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
            <div id="gamesBlankState" class="mt-3 text-center" hidden>
                <p>There are no games, create your first one!</p>
            </div>
        </main>

        <footer class="footer py-3 border-top border-body">
            <div class="container text-center">
                <span class="text-muted">PadelTime © 2024</span>
            </div>
        </footer>
    </div>

    <div class="modal fade" id="createGameModal" tabindex="-1" aria-labelledby="newGameModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="newGameModalLabel">New game</h5>
                    <button type="button" class="btn-close" id="newGameModalClose" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                    
                    <label for="slotDatetime" class="form-label">Select a date-time slot</label>
                    <div class="mb-3 alert alert-danger" id="newGameModalAlert" hidden></div>
                    <input type="datetime-local" class="form-control" id="newGameModalSlotInput" name="slotDatetime" required>
                    
                    <div class="mt-2 text-end">
                        <button id="newGameModalCreateBtn" type="button" class="btn btn-primary">Create</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirmDeleteModal" tabindex="-1" aria-labelledby="confirmDeleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="confirmDeleteModalLabel">Are you sure?</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this game?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger" id="confirmDeleteButton">Delete</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script>

        // Check if prefers-color-scheme is supported
        if (window.matchMedia('(prefers-color-scheme)').media !== 'not all') {
            // Listen for changes in the prefers-color-scheme media query
            window.matchMedia('(prefers-color-scheme: dark)').addListener(e => {
                const newTheme = e.matches ? 'dark' : 'light';
                document.documentElement.setAttribute('data-bs-theme', newTheme);
            });
        }
        // Set the initial theme based on prefers-color-scheme
        const initialTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
        document.documentElement.setAttribute('data-bs-theme', initialTheme);

        document.addEventListener("DOMContentLoaded", function () {
            const gamesTable = document.getElementById('gamesTable').getElementsByTagName('tbody')[0];
            const gamesBlankState = document.getElementById('gamesBlankState');
            
            const newGameModalAlert = document.getElementById('newGameModalAlert');
            const newGameModalSlotInput = document.getElementById('newGameModalSlotInput');
            const newGameModalCreateBtn = document.getElementById('newGameModalCreateBtn');
            const newGameModalClose = document.getElementById('newGameModalClose');

            function loadGames() {
                fetch('{{ url_for("api.search_games") }}', {
                    method: 'GET',
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        gamesBlankState.hidden = true;
                        gamesTable.innerHTML = '';
                        if (data.data.length > 0) {
                            data.data.forEach(function (game) {
                                const row = gamesTable.insertRow();
                                row.innerHTML = 
                                    `<td>${game.id}</td>
                                    <td>${new Date(game.slot).toLocaleString()}</td>
                                    <td>${game.created_by.email}</td>
                                    <td>${game.players.length}</td>
                                    <td>
                                        <span class="badge bg-${game.ready ? 'success' : 'danger'}">
                                            ${game.ready ? 'Yes' : 'No'}
                                        </span>
                                    <td>
                                        <button type="button" class="btn btn-outline-danger delete-game-btn" data-id="${game.id}">
                                            <i class="bi bi-trash3"></i>
                                        </button>
                                    </td>`;
                        });
                        } else {
                            gamesBlankState.hidden = false;
                        }
                    } else {
                        console.error(data.message);
                    }
                })
                .catch(function (error) {
                    console.error(error);
                });
            }

            loadGames();

            newGameModalCreateBtn.addEventListener('click', function () {
                const slot = newGameModalSlotInput.value + ":00";
                
                fetch('{{ url_for("api.create_game") }}', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        slots: [slot]
                    })
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        newGameModalAlert.hidden = true;
                        newGameModalSlotInput.value = '';
                        newGameModalSlotInput.classList.remove("is-invalid");
                        loadGames();
                        newGameModalClose.click();
                    } else {
                        newGameModalAlert.hidden = false;
                        newGameModalAlert.innerHTML = data.message;
                        newGameModalSlotInput.classList.toggle("is-invalid", true);
                        console.error(data.message);
                    }
                })
                .catch(function (error) {
                    console.error(error);
                })
            });

            function handleDeleteButtonClick(gameId) {
                const confirmDeleteModal = new bootstrap.Modal(document.getElementById('confirmDeleteModal'));
                confirmDeleteModal.show();
                confirmDeleteButton.addEventListener('click', function () {
                    fetch('/api/games/' + gameId, {
                        method: 'DELETE',
                        credentials: 'same-origin'
                    })
                        .then(response => response.json())
                        .then(data => {
                            if (data.success) {
                                loadGames();
                                confirmDeleteModal.hide();
                            } else {
                                console.error(data.message);
                            }
                        })
                        .catch(function (error) {
                            console.error(error);
                        });
                });
            }

            gamesTable.addEventListener('click', function (event) {
                const target = event.target;
                if (target.tagName === 'BUTTON' && target.classList.contains('delete-game-btn')) {
                    const gameId = parseInt(target.getAttribute('data-id'));
                    handleDeleteButtonClick(gameId);
                }
            });
        });
    </script>

</body>

</html>